output_dir: "oda-megane"
llm_type: "gemini"

# APIキー設定
llm_config:
  api_key: "API_KEY" # ここを自分のAPIキーに置き換える
  model_name: "gemini-1.5-pro"
  model:
    temperature: 0.9
    top_p: 0.95
    top_k: 64
    max_output_tokens: 8192

# 生成設定
generation:
  max_sections: 30 # 最大セクション数
  length: "3万字程度" # 物語の長さ

# 物語設定
story_setting: |
  『織田信長な彼女が尊すぎる件』 構成案
  主要キャラクター
  メインキャラクター

  主人公：佐藤一馬（さとう かずま）

  ごく普通の高校2年生
  前世の記憶に影響されない特殊体質
  メガネを拾ったことで騒動に巻き込まれる


  ヒロイン：綾小路美咲（あやこうじ みさき）

  生徒会長で学園一の美少女
  前世は織田信長
  普段は理知的だが、時々戦国武将モードが発動



  重要サブキャラクター

  親友：山田健一（やまだ けんいち）

  主人公の親友で、なんでも相談できる存在
  前世は聖徳太子
  法律や規則に異常にこだわる性格の理由が判明


  ミステリアス転校生：月城零（つきしろ れい）

  謎の転校生
  前世欄が「???」と表示される唯一の存在
  実は転生管理システムの監視官



  その他の個性的キャラクター

  柊 カレン（ひいらぎ かれん）

  帰国子女の美少女
  前世はジャンヌ・ダルク
  美咲のライバルで生徒会副会長


  鬼塚 竜司（おにづか りゅうじ）

  不良だが面倒見の良い先輩
  前世は坂本龍馬
  恋愛相談を持ちかけられる立場



  13フェイズ構造による展開
  第一幕：日常の崩壊
  ①背景・日常

  平凡な高校生活を送る主人公
  生徒会長・美咲への密かな想い
  クラスメイトたちとの何気ない交流

  ②異変・事件

  古びたメガネを拾う
  メガネ越しに見える「前世ステータス画面」の存在
  美咲が織田信長の転生者だと判明
  他のクラスメイトたちの意外な前世も次々と発覚

  ③実情・決意

  メガネの能力に戸惑いながらも活用を決意
  美咲との距離を縮めるチャンスと捉える
  時折垣間見える美咲の信長的言動に魅かれる

  第二幕：混沌の展開
  ④行動・吉凶

  メガネを使って前世相性の良い人たちを観察
  健一の前世が判明し、友情が深まる
  カレン（ジャンヌ・ダルク）が美咲にライバル心

  ⑤支援・助け

  零が転校してきて状況を把握
  前世の相性で惹かれ合う生徒が続出
  美咲が主人公に興味を持ち始める

  ⑥成長・工夫

  メガネの能力をうまく使いこなし始める
  美咲との関係が急速に深まる
  他の生徒たちの恋愛相談に乗り始める

  ⑦切望・転機

  美咲が時々本気の信長モードになり始める
  前世の記憶が覚醒する危険性が判明
  零から警告を受ける

  第三幕：危機と新展開
  ⑧困難・試練

  学校全体で前世の記憶覚醒が始まる
  美咲の信長化が進行
  生徒たちの人間関係が前世の因縁で複雑化

  ⑨危機・窮迫

  前世の記憶と現世の想いの狭間で揺れる美咲
  カレンとの決定的な対立
  零の正体が明らかに

  ⑩認識・死口

  前世と現世の調和の可能性を見出す
  美咲との想いが深まる
  新たな転生者の存在が示唆される

  ⑪対決・対決

  暴走する前世の記憶との戦い
  美咲との絆を確認
  カレンとの和解

  ⑫勝利・勝利

  美咲が前世の記憶と上手く折り合いをつける
  主人公との関係が深まる
  学園内の混乱が一時収束

  ⑬満足・満足（次巻への伏線）

  美咲との関係が進展
  新たな転生者の存在が示唆される
  より大きな危機の予感

  1フェイズ1,2セクションで作成したらよい。現在どこのフェイズを書いているのか常に意識すること。

# ログ設定
logging:
  level: INFO
  format: "%(asctime)s [%(levelname)s] %(message)s"
  file: "generation.log"
